name: Nightly

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  schedule:
    - cron: '0 0 * * 1,3,5'
  workflow_dispatch:

jobs:
  publish_nightly:
    name: Publish nightly
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        run: bash ./build-static.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Package
        env:
          ZSTD_CLEVEL: 19
          ZSTD_NBTHREADS: 2
        run: |
          cd static-installed
          tar -acf ../qv2ray-static-build-deps-nightly-${{ steps.date.outputs.date }}-archlinux-x86_64.tar.zst .
          cd ../QvMeta-build/installed
          tar -acf ../../qv2ray-static-bin-nightly-${{ steps.date.outputs.date }}-archlinux-x86_64.tar.zst .

      - name: Upload nightly release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: qv2ray-static-*-nightly-${{ steps.date.outputs.date }}-archlinux-x86_64.tar.zst
          tag: nightly-${{ steps.date.outputs.date }}
          file_glob: true
          overwrite: true
          prerelease: false
